### ISSUE TITLE
Function floor in Prism source-file should be of type int

### ISSUE THREAD

**Issue by merkste** [moves-rwth/storm#18]
If the function `floor` and the `init` statement are used in a prism source file, the parser throws the following error:

    ERROR (BaseExpression.cpp:45): Unable to evaluate expression as integer.
    ERROR (storm.cpp:14): An exception caused Storm to terminate. The message of the exception is: Unable to evaluate expression as integer.

In the minimal example below we can actually observe two issues. First (1.) if a constant is used in the variable definition and second, if floor is directly used in the definition.

    mdp
    
    const int MAX_output_ctr = floor(2.5);
    
    init
      true
    endinit
    
    module output_chan
      output_ctr : [0 .. MAX_output_ctr];  // 1.
      //  output_ctr : [0 .. floor(2.5)];  // 2.
    
      [tick] true -> true;
    endmodule

**Comment by cdehnert** [comment]
My last commit fixes half of the problem (the half that makes the above example work as is). It does not yet fix the issue with putting the function invocation directly in the variable bounds.

**Comment by cdehnert** [comment]
I just committed a fix to the second issue. We resolve it by disallowing double literals with trailing dots just like PRISM does, but allowing double literals with leading dots. I don't like this inconsistency, but otherwise the PRISM language is ambiguous to parse. Anyway, can you please check whether the latest commit resolves the issue for you and close the issue if so?

**Comment by merkste** [comment]
Thanks a lot! I'll test it as soon as I reinstalled storm.

**Comment by merkste** [comment]
I tried it today on a linux system and the fixes were successful. Thanks a lot for the fast reaction!
