### ISSUE TITLE
Cannot set dft:approximationheuristic to anything other than `depth`

### ISSUE THREAD

**Issue by kris7t** [moves-rwth/storm#35]
It is impossible to set an approximation heuristic any other than `depth` for DFTs.

https://github.com/moves-rwth/storm/blob/47b2cb737d84208f4081bf8c5910d0d0997e26d7/src/storm-dft/settings/modules/FaultTreeSettings.cpp#L34 sets up the command line option such that in only accepts the values `depth` and `rateratio`. However, in https://github.com/moves-rwth/storm/blob/47b2cb737d84208f4081bf8c5910d0d0997e26d7/src/storm-dft/settings/modules/FaultTreeSettings.cpp#L66-L71 only the values `depth` and `probability` are accepted. Thus only `depth` is accepted by both validations.

What is supposed to be the correct option here?

**Comment by volkm** [comment]
This should be fixed now in the current `master` branch. I apologize for the long time it took to fix this issue. It took longer than anticipated because apart from the problems of setting the heuristic on the command line, using the correct approximation heuristic in the state space generation was also broken.

`Storm-dft` now supports three different heuristics for the state space generation:
- `depth`: explores the state space in a breadth-first manner. States with the shortest path to the initial state have the highest priority.
- `probability`: states with the highest reachability probability are explored first. This heuristic should focus on the part of the state space which contains the most probability mass.
- `bounddifference`: this heuristic uses the approximate results from the previous iteration. States with a great difference between lower and upper value get a higher priority. This heuristic should explore states where the approximative results is not yet precise enough.

If you encounter any problems, let me know.
