### ISSUE TITLE
Build step for carl fails

### ISSUE THREAD

**Issue by HansvdLaan** [moves-rwth/storm#39]
When following the Building Storm from Source tutorial, I get the following error at the _make_ step. I got no error during the _cmake_ step. All the dependencies are installed. 

![image](https://user-images.githubusercontent.com/9132846/55340257-9a344f80-54a4-11e9-87e1-509c43eb5afb.png)

Trying to build carl manually gives the following error:

![](https://user-images.githubusercontent.com/9132846/55340214-84268f00-54a4-11e9-830b-fcb14e6ccd96.png)

<details>
  <summary>Commands I tried to build carl manually</summary>
  
```
$ git clone -b master14 https://github.com/smtrat/carl.git
$ cd carl
Prepare the build:

$ mkdir build && cd build
$ cmake .. -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON
Build lib_carl:

$ make lib_carl
```
Inspired by : https://moves-rwth.github.io/prophesy/installation.html
</details>

**Comment by volkm** [comment]
The problem is in the manual installation of Eigen3, but I could not reproduce the error on my machine. What operating system are you using?
You can also try to remove both the Storm and the Carl directory and manually build Carl once again. Does the error persist then?

These steps help us figuring out the underlying problem. If you just want to have a running version of Storm I recommend to install the Eigen3 package:
`sudo apt-get install libeigen3-dev`

**Comment by HansvdLaan** [comment]
I was working with a fresh new install of the latest release of debian (for a VM).

Your solution worked. After removing both directories, first building Carl before Storm fixed the issue. 

Thanks a lot!
