### ISSUE TITLE
Bug with Markov Automata PRISM file input

### ISSUE THREAD

**Issue by charlie1329** [moves-rwth/storm#43]
The following file:
```
ma
 
module M 
 
s:[0..2] init 0;

[](s=0) -> 0.06:(s'=1) + 0.94:(s'=2);

endmodule
```
 when input with `storm --prism file.ma` returns the following error:

`ERROR (MarkovAutomaton.cpp:160): Entries of transition matrix do not sum up to one for (non-Markovian) choice 0 of state 0 (sum is 1).
ERROR (storm.cpp:14): An exception caused Storm to terminate. The message of the exception is: Entries of transition matrix do not sum up to one for (non-Markovian) choice 0 of state 0 (sum is 1).`

If I change the probabilities to 0.05 & 0.95 or 0.04 & 0.96 for example, the model is successfully built. Additionally, if I change the model at the top of the file from ma to mdp, the model also successfully builds.

**Comment by volkm** [comment]
Thanks for the report.
The problem comes from imprecisions when dealing with floating point arithmetic. In your example `0.06` and `0.94` can only be approximated by doubles and the resulting sum is `0.99999999999999978` which is not considered equal to `1`.

We fixed it in 15dadf1 by using a comparison which respects the required precision (default is `1e-6`).

**Comment by charlie1329** [comment]
Thanks for the quick response. I'll test the new commit and close the commit if all is good!

**Comment by charlie1329** [comment]
Sorry for the delay, I've checked this now and the bug appears to be fixed so I shall close the issue.
