### ISSUE TITLE
Making Sylvan the default BDD engine

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#71]
Hello,

we are considering changing the default BDD engine to sylvan. 

Before we make this change,
- is it necessary to add a warning notifying users of this change?
- is there any reason not to change?

**Comment by volkm** [comment]
I second the change to Sylvan.
In my opinion we do not need to warn users. From a user perspective the change should not be noticeable so much, because the functionality should stay the same. The performance might differ, but one can always explicitly set the DD library if necessary.
We should however mention the change in the Changelog.

**Comment by tquatmann** [comment]
I now changed the default (without printing an explicit warning). Hope you all agree.
