### ISSUE TITLE
TerminationCondition/Empty Filter for Bounded Formulae

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#87]
Hi,

I do not understand the following error message.

Best, 
Sebastian

```
Storm 1.6.3 (dev)
DEBUG BUILD

Command line arguments: -drn unrolling.out --prop 'Pmax<=0.01 [F "_goal"]'

Time for model construction: 0.006s.

-------------------------------------------------------------- 
Model type: 	MDP (sparse)
States: 	16
Transitions: 	37
Choices: 	25
Reward Models:  none
State Labels: 	2 labels
   * init -> 1 item(s)
   * _goal -> 1 item(s)
Choice Labels: 	none
-------------------------------------------------------------- 

Model checking property "1": Pmax<=1/100 [F "_goal"] ...
ERROR (TerminationCondition.cpp:104): Empty Filter; Can not take extremum over empty set.
 WARN (model-handling.h:885): Cannot handle property: InvalidArgumentException: Empty Filter; Can not take extremum over empty set.
ERROR (model-handling.h:847): Property is unsupported by selected engine/settings.

```

[unrolling.out.txt](https://github.com/moves-rwth/storm/files/5265745/unrolling.out.txt)

I added the txt to upload  the file.

**Comment by tquatmann** [comment]
The problem here is that the only relevant state for the property (the initial state) is already in `S_{=1}`, i.e. it has probability 1. Hence, the `TerminationCondition` for quantitative model checking complained that there is no relevant state (within the `S_?` set) to filter for.

Actually, there shouldn't be any quantiatative computations in the first place.

I'm pushing a fix soon.
