### ISSUE TITLE
Support for Visual Studio Compiler

### ISSUE THREAD

**Issue by Necktschnagge** [moves-rwth/storm#92]
Is there a specific reason why the MSVC++ compiler is not supported?

**Comment by tquatmann** [comment]
In it's early days, Storm actually had support for MSVC. We dropped it when [carl](https://github.com/smtrat/carl) became a mandatory prerequisite, simply because carl didn't support MSVC. Back then, there were also quite a few `c++11` features that were not properly supported by MSVC. So there was a bit of extra work required and oftentimes someone unknowingly broke the MSVC build.

Nowadays, we could probably re-consider supporting MSVC but this is not very high on our list, especially because Windows users can fall back to Windows Subsystem for Linux or a Docker container.
