### ISSUE TITLE
LTL in Multi-objective query

### ISSUE THREAD

**Issue by kld40dk** [moves-rwth/storm#93]
I have a prism property file (see example below) that works fine in prism (the result is also what I expect) but storm fails to compile.

Is this a parser issue or does storm only accept a subset of the prism language? If the latter, could you provide an insight on how to translate the file to the subset accepted by storm?

Prism model:
```
mdp
formula done = var3=0 & var0=1 & var1=1;
module test_problem
// Variables
var0: [0..1] init 1;
var1: [0..1] init 1;
var2: [0..1] init 1;
var3: [0..1] init 1;

// Actions
[a1] !done & var0=0 -> 1: (var2'=0);
[a2] !done & var2=0 & var1=0 -> 0.8: (var3'=0) & (var2'=1) + 0.2: (var2'=1);
[a3] !done & var0=0 -> 1: (var0'=1);
[a4] !done & var1=0 -> 1: (var1'=1);
[a5] !done & var0=1 -> 1: (var0'=0);
[a6] !done & var1=1 -> 1: (var1'=0);
[] done -> true;
endmodule
```

Prism property file:
```
multi(R{"actions"}min=? [ C ],
  P >= 1 [ F done ],
  P >= 1 [ F var0=0 ],
  P >= 1 [ G ((var0!=0 ) | (var0=0 U (var1=0  & (G (var0!=0 ))))) ]
)
```

Prism works fine using: ```./prism -lp model.prism property.csl``` and ```./storm --prism model.prism --prop property.csl``` outputs:
```
ERROR (SpiritErrorHandler.h:26): Parsing error at 4:10:  expecting ")", here:
	 (var0=0 U (var1=0  & (G (var0!=0 ))))) ]
	         ^

ERROR (storm.cpp:26): An unexpected exception occurred and caused Storm to terminate. The message of this exception is: std::exception
```

I'm running storm 1.6.2

Thanks!

**Comment by sjunges** [comment]
Hi,

let me just quickly clarify what the problem here is, without providing a solution yet. 
The same error happens if you put in` P>=1 [ G (true U true) ]`, but it does not occur with ` P>=1 [ G true ]`. Why?
The formula you provided is not a PCTL formula. In particular, ` G (true U true)` is an LTL formula, and we currently not support LTL. @tquatmann  might tell you more. 

Thus, the problem is more fundamental than a syntax query. 
Furthermore, you are using the formula inside a multi objective query. That is going to affect whether we can provide support as well.  I have not looked into the model to closely, but if you can formulate the problem without nesting temporal operators, we should be able to support the query.  One way is to manually build the automaton that accepts this LTL formula and add that to the model.... 

Alternatively, I think that the model can be simplified by looking at the formula if I understand the formula correctly, it implies that once you have var0=0, this never changes anymore.

**Comment by sjunges** [comment]
The parser error is now a separate issue: #94

**Comment by tquatmann** [comment]
I can confirm what @sjunges said. We currrently do not have support for LTL. 
The supported properties of Storm and Prism are incomparable, since we also support properties that PRISM does not support, such as, e.g., reward-bounded reachability probabilities.

For your property, I would suggest (similar to Sebastian) to encode the "P>=1 ..." sub-properties somehow in the model. For example, you can use a boolean variable that "remembers" when var0=0 was once true. As far as I can see, it is possible to reduce this to just a single-objective formula `R{"actions"}min=? [F condition]` (Note that if `condition` is not reached with probability 1, the reward is defined as infinity. Hence, if the value for this property is not infinity, we know that it is attained by a scheduler that reaches `condition` with probability 1). That approach would scale to rather big models, as well.
If needed, we can offer further help with that.

**Comment by kld40dk** [comment]
Thanks a lot @sjunges and @tquatmann for the quick response and pointers to reformulate the problem!
