### ISSUE TITLE
C++ APIs to obtain closed form solution of parametric model checking.

### ISSUE THREAD

**Issue by huypn12** [moves-rwth/storm#96]
Hi Storm team, 

It is not an issue, I have a small question. I am doing parameter synthesis with Storm. As I can see in the [Example 5](https://www.stormchecker.org/documentation/usage/running-storm.html#example-5-obtaining-closed-form-solutions-for-parametric-models), `storm-pars` support obtaining the closed form solution for a certain property of a parametric model.
However, my question is:
1. How can I do it with C++ API of Storm (I mean, programmatically), rather than executing storm-pars for a certain model file and parse the result?
2. Does Storm support also parametric model for Markov Decision Process?

Thank you,

**Comment by volkm** [comment]
Hi,

I attached a [small program](https://github.com/moves-rwth/storm/files/5615105/main.txt) which computes the rational function for a pDTMC. The example program is a modified version of our [C++ starter project](https://github.com/moves-rwth/storm-project-starter-cpp). As you can see, the main difference is that we are using `storm::RationalFunction` instead of `double` as the underlying data type now.
(Note that I changed the file extension from `.cpp` to `.txt` to upload it on Github.)

A good starting point for further features is also our [API for storm-pars](https://github.com/moves-rwth/storm/tree/master/src/storm-pars/api).

For MDPs, we do not compute a rational function, because we would obtain a different rational function for each scheduler/policy for the non-deterministic choices. Instead, we perform parameter synthesis by dividing the parameter space into regions and checking which regions (i.e. which parameter valuations) satisfy the property, and which do not. The background of this idea is explained in [chapter VII of our paper](https://arxiv.org/abs/1903.07993).
An example of using this approach via C++ can be found in our [tests](https://github.com/moves-rwth/storm/blob/master/src/test/storm-pars/modelchecker/SparseMdpParameterLiftingTest.cpp#L56).

I hope that gets you started.

Best,
Matthias

**Comment by huypn12** [comment]
Niceeeeee!!!!!!
